server:
  port:80
spring:
  application:
    name: book-my-ticket
  datasource:
    url: jdbc:mysql://localhost:3306/employee?createDatabaseIfNotExist=true
    username: root
    password: Bhoomi
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql:
  data:
    redis:
      url: redis://localhost:6379